spring:
  application:
    name: mdf-test-consumer
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
dubbo:
  application:
    name: mdf-test-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
mdf:
    log:
      web:
        enable: true
      dubbo:
        enable: true
      desensitize:
        enable: true
        addDefaultGlobalRules: false
        customizeRules:
          - keys: phoneNumber,mobileNo
            regex: '1[3-9]\d{9}'
            position: 3,4
          - keys: idCard
            regex: '[1-9]\d{5}\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])\d{3}|[1-9]\d{5}(18|19|20)\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])\d{3}[0-9Xx]'
            position: 6,4
          - keys: bankCard
            regex: '62[0-9]{14,17}|4[0-9]{15}|5[1-5][0-9]{14}|(34|37)[0-9]{13}|35[0-9]{14}'
            position: 4,4