spring:
  application:
    name: mdf-test-consumer
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
dubbo:
  application:
    name: mdf-test-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
